SUBROUTINE MINF(N, FUNCT, VOISIN, EPSIL, X, FX)
IMPLICIT REAL*8(A-H,O-Z)
EXTERNAL FUNCT
DIMENSION X(1)
DIMENSION Y(100), S(100)
IF(N.GT.100) RETURN
DELTA=VOISIN
R0=0.1
DO 1 K=1,N
1 S(K)=DELTA
FX=FUNCT(N,X)
2 FY=FX
DO 3 K=1,N
3 Y(K)=X(K)
ITER=ITER+l
CALL MINIF(N,FUNCT,Y,S,FY)
IF(FY.LT.FX) GOTO 6
4 IF(DELTA.LT.EPSIL) RETURN
DELTA=R0*DELTA
DO 5 K=1,N
5 S(K)=R0*S(K)
GOTO 2
6 DO 7 K=1,N
IF(S(K)*(Y(K)-X(K)) .LT. 0.0) S(K)=-S(K)
TETA=X(K)
X(K)=Y(K)
7 Y(K)=Y(K)+Y(K)-TETA
FX=FY
FY=FUNCT(N,Y)
CALL MINIF(N,FUNCT,Y,S,FY)
IF(FY.GE.FX) GOTO 2
DO 8 K=1,N
IF(DABS(Y(K)-X(K)) .GT. 0.5*DABS(S(K))) goto 6
8 CONTINUE
GOTO 4
END

SUBROUTINE MINIF(N,FUNCT,X,S,FX)
IMPLICIT REAL*8(A-H,O-Z)
DIMENSION X(l),S(l)
DO 3 K=1,N
X(K)=X(K)+S(K)
F=FUNCT(N,X)
IF(F.GE.FX) GOTO 1
FX=F
GOTO 3
1 X(K)=X(K)-S(K)-S(K)
F=FUNCT(N,X)
IF(F.GE.FX) GOTO 2
FX=F
S(K)=-S(K)
GOTO 3
2 X(K)=X(K)+S(K)
3 CONTINUE
RETURN
END

FUNCTION F(N,X)
IMPLICIT REAL*8(A-H,O-Z)
DIMENSION X(2)
A=X(1)
B=X(2)
F=A*A+100.0*B*B
RETURN
END

PROGRAM MAIN
IMPLICIT REAL*8(A-H,O-Z)
EXTERNAL F
DIMENSION X(2)
X(1)=100.0
X(2)=200.0
CALL MINF(2, F, 10, 0.01, X, FX)
PRINT *, X, FX
END